export const POKE_CONTENT_REQUEST = "POKE_CONTENT_REQUEST"
export const POKE_CONTENT_SUCCESS = "POKE_CONTENT_SUCCESS"
export const POKE_CONTENT_FAIL = "POKE_CONTENT_FAIL"

export const POKE_CONTENT_BYID_REQUEST = "POKE_BYIDCONTENT_REQUEST"
export const POKE_CONTENTBYID_SUCCESS = "POKE_BYIDCONTENT_SUCCESS"
export const POKE_CONTENTBYID_FAIL = "POKE_BYIDCONTENT_FAIL"